// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace VolumetricShader.Effects
{
    public static partial class VolumetricSphereKeys
    {
        public static readonly ValueParameterKey<float> MAX_STEPS = ParameterKeys.NewValue<float>(100);
        public static readonly ValueParameterKey<float> MAX_DIST = ParameterKeys.NewValue<float>(100);
        public static readonly ValueParameterKey<float> SURF_DIST = ParameterKeys.NewValue<float>(1e-2f);
        public static readonly ValueParameterKey<Vector3> CameraPos = ParameterKeys.NewValue<Vector3>(new Vector3(0,0,-3));
    }
}
